services:
  - type: web
    name: my-node-app
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free